/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package threads;

public class App {
    public static void main(String[] args) {
        new MinhaThread("1").start();
        new MinhaThread("2").start();
    }
}
