/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exerciciofiltroassembler;

import java.io.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        BufferedInputStream input;


        System.out.println("Digite o nome do arquivo de entrada: ");
        String arquivoEntrada = scanner.nextLine();
        System.out.println("Digite o nome do arquivo de saida: ");
        String arquivoSaida = scanner.nextLine();

        try {
            input = new BufferedInputStream(new FileInputStream(arquivoEntrada));
            OutputStream output = new FileOutputStream(arquivoSaida);
                
            int data = input.read();
            int contagemLinhas = 1;

            String inicioDaLinha = "db ";
            String finalDaLinha = "; linha ";

            while (data != -1) {
                // Arquivo comeca com db na linha
                for (int i = 0; i < inicioDaLinha.length(); i++) {
                    output.write(inicioDaLinha.charAt(i));
                }

                for (int i= 0; i < 8; i++) {
                    data = input.read();

                    output.write((byte) data);
                    output.write(',');
                    output.write(' ');
                }

                for (int i = 0; i < finalDaLinha.length(); i++) {
                    output.write(finalDaLinha.charAt(i));

                }

                String linhaAtual = Integer.toString(contagemLinhas);
                for (int i = 0; i < linhaAtual.length(); i++) {
                    output.write(linhaAtual.charAt(i));
                }
                output.write('\n');
                contagemLinhas++;
            }

            input.close();
            output.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
